# Generated by Django 4.2.23 on 2025-07-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("dead_time", models.DateTimeField()),
                ("start_time", models.DateTimeField()),
                ("spending_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("late", "Be Late"),
                            ("working", "on working"),
                            ("wait", "wiating for start"),
                        ],
                        default="wait",
                        max_length=10,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_manager",
                        to="account.profile",
                    ),
                ),
                ("related_user", models.ManyToManyField(to="account.profile")),
            ],
        ),
        migrations.CreateModel(
            name="SubProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("dead_time", models.DateTimeField()),
                ("start_time", models.DateTimeField()),
                ("spending_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("late", "Be Late"),
                            ("working", "on working"),
                            ("wait", "wiating for start"),
                        ],
                        default="wait",
                        max_length=10,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_project_manager",
                        to="account.profile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.project"
                    ),
                ),
                (
                    "related_user",
                    models.ManyToManyField(
                        related_name="sub_project_user", to="account.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("dead_time", models.DateTimeField()),
                ("start_time", models.DateTimeField()),
                ("spending_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("late", "Be Late"),
                            ("working", "on working"),
                            ("wait", "wiating for start"),
                        ],
                        default="wait",
                        max_length=10,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_manager",
                        to="account.profile",
                    ),
                ),
                (
                    "related_user",
                    models.ManyToManyField(
                        related_name="task_user", to="account.profile"
                    ),
                ),
                (
                    "sub_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task.subproject",
                    ),
                ),
            ],
        ),
    ]
