# Generated by Django 4.2.23 on 2025-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_project_spending_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="spending_time",
            field=models.IntegerField(default=0, help_text="minutes of Spending time"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="spending_time",
            field=models.IntegerField(default=0, help_text="minutes of Spending time"),
        ),
        migrations.AlterField(
            model_name="task",
            name="spending_time",
            field=models.IntegerField(default=0, help_text="minutes of Spending time"),
        ),
    ]
